"""Runtime Core public contracts.

This namespace owns one Agent Run's lifecycle and the ports needed to execute
it. Integrations that need concrete storage, provider, or telemetry adapters
should import those from :mod:`m_agent.adapters` instead.
"""

from .._clock import Clock
from .._codec import PayloadCodec
from .._context import ContextItem, ContextProvider, ContextRequest
from .._definition import (
    AgentDefinition,
    DefinitionRegistry,
    DefinitionSnapshot,
    RetryPolicy,
)
from .._history import ConversationMessage, ConversationRole
from .._output import OutputContract, OutputFallback, OutputRepairPolicy
from .._policy import (
    AllowAllRunPolicy,
    PolicyAction,
    PolicyDecision,
    PolicyDecisionRecord,
    PolicyGate,
    PolicyIdentity,
    PolicyRequest,
    RunPolicy,
    StaticRunPolicy,
)
from .._errors import (
    DefinitionConflictError,
    DefinitionNotFoundError,
    DuplicateRunError,
    IllegalRunTransitionError,
    LeaseNotHeldError,
    MAgentError,
    ModelCapabilityError,
    ModelContractViolationError,
    ResolutionNotAllowedError,
    RunNotFoundError,
    StaleRunVersionError,
)
from .._failure import ModelFailure, StepFailure, ToolFailure
from .._model import (
    ModelAdapter,
    ModelBinding,
    ModelBindingSet,
    ModelCapabilityCombination,
    ModelCapabilities,
    ModelContract,
    ModelDelta,
    ModelExecutionBudget,
    ModelLimits,
    ModelPurpose,
    ModelRequest,
    ModelRequirementMatch,
    ModelRequirementReason,
    ModelRequirements,
    ModelResponse,
    ModelUsage,
    ModelUsageGuarantees,
    RevisionStability,
    StreamingMode,
    StructuredOutputMode,
    ToolCallingMode,
    UsageFieldGuarantee,
    UsageProvenance,
    UsageReportingMode,
)
from .._resolution import (
    ALLOWED_FOR_DEFINITION_UNAVAILABLE,
    ALLOWED_FOR_UNCERTAIN_NON_IDEMPOTENT,
    ResolutionAction,
    RunResolution,
    allowed_resolutions,
)
from .._run import RunInspection, RunRecord
from .._runner import (
    CrashPoint,
    DEFAULT_LEASE_TTL,
    ERROR_EFFECT_UNCONFIRMED,
    ERROR_MODEL_EXECUTION_BUDGET_EXCEEDED,
    ERROR_OUTPUT_VALIDATION_FAILED,
    ERROR_POLICY_ERROR,
    REASON_DEFINITION_UNAVAILABLE,
    REASON_POLICY_RESOLUTION_REQUIRED,
    REASON_UNCERTAIN_NON_IDEMPOTENT,
    Runner,
    deserialize_model_response,
    serialize_model_response,
    deserialize_tool_outcome,
    serialize_tool_outcome,
)
from .._status import RunStatus, is_terminal
from .._steps import (
    FailureClassification,
    StepAttempt,
    StepCheckpoint,
    StepRecord,
    StepStatus,
    StepType,
)
from .._store import RunLease, RunStore
from .._sync import SyncRunner
from .._telemetry import TelemetryEvent, TelemetryEventType, TelemetrySink
from .._tools import (
    DEFAULT_TOOL_PARAMETERS,
    Tool,
    ToolCall,
    ToolDeclaration,
    ToolEffect,
    ToolOutcome,
    ToolOutcomeStatus,
    ToolRequest,
    ToolSpec,
)
from .._updates import RunUpdate, RunUpdateType

__all__ = [
    "AgentDefinition",
    "AllowAllRunPolicy",
    "ALLOWED_FOR_DEFINITION_UNAVAILABLE",
    "ALLOWED_FOR_UNCERTAIN_NON_IDEMPOTENT",
    "Clock",
    "CrashPoint",
    "ContextItem",
    "ContextProvider",
    "ContextRequest",
    "ConversationMessage",
    "ConversationRole",
    "DEFAULT_LEASE_TTL",
    "DEFAULT_TOOL_PARAMETERS",
    "DefinitionConflictError",
    "DefinitionNotFoundError",
    "DefinitionRegistry",
    "DefinitionSnapshot",
    "DuplicateRunError",
    "deserialize_model_response",
    "deserialize_tool_outcome",
    "ERROR_EFFECT_UNCONFIRMED",
    "ERROR_MODEL_EXECUTION_BUDGET_EXCEEDED",
    "ERROR_OUTPUT_VALIDATION_FAILED",
    "ERROR_POLICY_ERROR",
    "FailureClassification",
    "IllegalRunTransitionError",
    "LeaseNotHeldError",
    "MAgentError",
    "ModelAdapter",
    "ModelBinding",
    "ModelBindingSet",
    "ModelCapabilityCombination",
    "ModelCapabilities",
    "ModelCapabilityError",
    "ModelContractViolationError",
    "ModelContract",
    "ModelDelta",
    "ModelExecutionBudget",
    "ModelLimits",
    "ModelPurpose",
    "ModelFailure",
    "ModelRequest",
    "ModelRequirementMatch",
    "ModelRequirementReason",
    "ModelRequirements",
    "ModelResponse",
    "ModelUsage",
    "ModelUsageGuarantees",
    "OutputContract",
    "OutputFallback",
    "OutputRepairPolicy",
    "PayloadCodec",
    "PolicyAction",
    "PolicyDecision",
    "PolicyDecisionRecord",
    "PolicyGate",
    "PolicyIdentity",
    "PolicyRequest",
    "REASON_DEFINITION_UNAVAILABLE",
    "REASON_POLICY_RESOLUTION_REQUIRED",
    "REASON_UNCERTAIN_NON_IDEMPOTENT",
    "ResolutionAction",
    "ResolutionNotAllowedError",
    "RetryPolicy",
    "RunInspection",
    "RunLease",
    "RunNotFoundError",
    "RunRecord",
    "RunPolicy",
    "Runner",
    "RunResolution",
    "RunStatus",
    "RunStore",
    "RunUpdate",
    "RunUpdateType",
    "serialize_model_response",
    "serialize_tool_outcome",
    "RevisionStability",
    "StreamingMode",
    "StaleRunVersionError",
    "StepAttempt",
    "StepCheckpoint",
    "StepFailure",
    "StepRecord",
    "StepStatus",
    "StepType",
    "StaticRunPolicy",
    "StructuredOutputMode",
    "SyncRunner",
    "TelemetryEvent",
    "TelemetryEventType",
    "TelemetrySink",
    "Tool",
    "ToolCall",
    "ToolCallingMode",
    "ToolDeclaration",
    "ToolEffect",
    "ToolFailure",
    "ToolOutcome",
    "ToolOutcomeStatus",
    "ToolRequest",
    "ToolSpec",
    "allowed_resolutions",
    "is_terminal",
    "UsageFieldGuarantee",
    "UsageProvenance",
    "UsageReportingMode",
]
