"""Model Routing Companion（ADR 0041，Ticket 19）。

在 ``create_run`` 之前用冻结的 Model Catalog、版本化 Routing
Policy、Deployment Constraints 与只读 evidence snapshot 确定性选择
完整 Agent Variant。Router 是纯函数 Runtime Companion：只组合公开契约
（``m_agent.runtime`` 的 Model Contract / Requirements / Binding Set）
与快照输入，不读取原始 prompt、Conversation History 或敏感 Context
Item，不向 Runtime Core 引入 catalog、pricing、availability 或
selection algorithm，也不实现快照获取/更新机制、Model Fallback、
Run 内换模或 Recommendation 发布闭环（Ticket 20）。
"""

from ._catalog import (
    AgentVariant,
    DeploymentAttributes,
    ModelCatalog,
    ModelCatalogEntry,
)
from ._evidence import (
    AvailabilitySnapshot,
    ModelEvidenceSnapshot,
    PricingSnapshot,
    RetentionEvidenceSnapshot,
    RoutingEvidence,
)
from ._policy import (
    DeploymentConstraints,
    HardRoutingGates,
    MissingValuePolicy,
    ObjectiveDirection,
    ObjectiveDimension,
    RoutingObjective,
    RoutingPolicy,
    RoutingPolicyIdentity,
)
from ._router import (
    CandidateEvaluation,
    CandidateEvaluationStage,
    EvidenceSnapshotReference,
    ModelRouter,
    ObjectiveValue,
    RoutingBindingError,
    RoutingDecision,
    RoutingDecisionBinding,
    RoutingError,
    RoutingOutcome,
    RoutingResult,
    RoutingWarning,
    WARNING_SOFT_EVIDENCE_MISSING,
    WARNING_SOFT_EVIDENCE_STALE,
    bind_decision_to_run,
)
from ._router import (
    REASON_AMBIGUOUS_OBJECTIVES,
    REASON_AVAILABILITY_SNAPSHOT_MISSING,
    REASON_AVAILABILITY_SNAPSHOT_STALE,
    REASON_CONTRACT_FINGERPRINT_CONFLICT,
    REASON_DUPLICATE_VARIANT_IDENTITY,
    REASON_EMPTY_CANDIDATE_SCOPE,
    REASON_ENDPOINT_CLASS_NOT_ALLOWED,
    REASON_ENDPOINT_CLASS_UNKNOWN,
    REASON_HARD_AVAILABILITY_GATE_FAILED,
    REASON_HARD_PRICE_GATE_FAILED,
    REASON_HARD_QUALITY_GATE_FAILED,
    REASON_HARD_STABILITY_GATE_FAILED,
    REASON_MODEL_EVIDENCE_MISSING,
    REASON_MODEL_EVIDENCE_STALE,
    REASON_NOT_IN_CANDIDATE_SCOPE,
    REASON_NOT_REGISTERED_FOR_POLICY,
    REASON_NO_COMPATIBLE_VARIANT,
    REASON_OUTRANKED,
    REASON_POLICY_UNSATISFIED,
    REASON_PRICING_SNAPSHOT_MISSING,
    REASON_PRICING_SNAPSHOT_NOT_EFFECTIVE,
    REASON_PRICING_SNAPSHOT_STALE,
    REASON_PROVIDER_NOT_ALLOWED,
    REASON_PROVIDER_UNKNOWN,
    REASON_REGION_NOT_ALLOWED,
    REASON_REGION_UNKNOWN,
    REASON_RETENTION_EVIDENCE_MISSING,
    REASON_RETENTION_EVIDENCE_STALE,
    REASON_RETENTION_EVIDENCE_UNKNOWN,
    REASON_RETENTION_EVIDENCE_VERSION_MISMATCH,
    REASON_RETENTION_EVIDENCE_VERSION_NOT_ALLOWED,
    REASON_SELECTED,
)

__all__ = [
    "AgentVariant",
    "AvailabilitySnapshot",
    "CandidateEvaluation",
    "CandidateEvaluationStage",
    "DeploymentAttributes",
    "DeploymentConstraints",
    "EvidenceSnapshotReference",
    "HardRoutingGates",
    "MissingValuePolicy",
    "ModelCatalog",
    "ModelCatalogEntry",
    "ModelEvidenceSnapshot",
    "ModelRouter",
    "ObjectiveDimension",
    "ObjectiveDirection",
    "ObjectiveValue",
    "PricingSnapshot",
    "REASON_AMBIGUOUS_OBJECTIVES",
    "REASON_AVAILABILITY_SNAPSHOT_MISSING",
    "REASON_AVAILABILITY_SNAPSHOT_STALE",
    "REASON_CONTRACT_FINGERPRINT_CONFLICT",
    "REASON_DUPLICATE_VARIANT_IDENTITY",
    "REASON_EMPTY_CANDIDATE_SCOPE",
    "REASON_ENDPOINT_CLASS_NOT_ALLOWED",
    "REASON_ENDPOINT_CLASS_UNKNOWN",
    "REASON_HARD_AVAILABILITY_GATE_FAILED",
    "REASON_HARD_PRICE_GATE_FAILED",
    "REASON_HARD_QUALITY_GATE_FAILED",
    "REASON_HARD_STABILITY_GATE_FAILED",
    "REASON_MODEL_EVIDENCE_MISSING",
    "REASON_MODEL_EVIDENCE_STALE",
    "REASON_NOT_IN_CANDIDATE_SCOPE",
    "REASON_NOT_REGISTERED_FOR_POLICY",
    "REASON_NO_COMPATIBLE_VARIANT",
    "REASON_OUTRANKED",
    "REASON_POLICY_UNSATISFIED",
    "REASON_PRICING_SNAPSHOT_MISSING",
    "REASON_PRICING_SNAPSHOT_NOT_EFFECTIVE",
    "REASON_PRICING_SNAPSHOT_STALE",
    "REASON_PROVIDER_NOT_ALLOWED",
    "REASON_PROVIDER_UNKNOWN",
    "REASON_REGION_NOT_ALLOWED",
    "REASON_REGION_UNKNOWN",
    "REASON_RETENTION_EVIDENCE_MISSING",
    "REASON_RETENTION_EVIDENCE_STALE",
    "REASON_RETENTION_EVIDENCE_UNKNOWN",
    "REASON_RETENTION_EVIDENCE_VERSION_MISMATCH",
    "REASON_RETENTION_EVIDENCE_VERSION_NOT_ALLOWED",
    "REASON_SELECTED",
    "RetentionEvidenceSnapshot",
    "RoutingBindingError",
    "RoutingDecision",
    "RoutingDecisionBinding",
    "RoutingError",
    "RoutingEvidence",
    "RoutingObjective",
    "RoutingOutcome",
    "RoutingPolicy",
    "RoutingPolicyIdentity",
    "RoutingResult",
    "RoutingWarning",
    "WARNING_SOFT_EVIDENCE_MISSING",
    "WARNING_SOFT_EVIDENCE_STALE",
    "bind_decision_to_run",
]
